CREATE OR REPLACE PROCEDURE ADD_ORDER(
EMPID IN CHAR,
ONLINE_PARTNER IN VARCHAR2,
CUSTID IN CHAR) IS
ORDER_ID ORDERS.ORDERID%TYPE;
BEGIN
SELECT NEXT_ORDERID INTO ORDER_ID FROM REFERENCE_VARIABLES;
INSERT INTO ORDERS VALUES(ORDER_ID, SYSDATE, EMPID, ONLINE_PARTNER, CUSTID);
END;
/

CREATE OR REPLACE PROCEDURE SUPPLY_ORDER(
SUPP_NAME IN VARCHAR2,
BATCH_NO IN VARCHAR,
ITEM_NAME IN VARCHAR,
MFD IN DATE,
EXP IN DATE,
CP IN NUMBER,
SP IN NUMBER,
QUANTITY IN NUMBER,
MANUFACTURER_NAME IN OUT VARCHAR) IS
MANU MANUFACTURER.NAME%TYPE;
BEGIN
SELECT NAME INTO MANU FROM MANUFACTURER WHERE NAME = MANUFACTURER_NAME;

INSERT INTO ITEM
VALUES(BATCH_NO,ITEM_NAME,MFD,EXP,CP,SP,QUANTITY,MANUFACTURER_NAME);
INSERT INTO SUPPLY_TRANSACTIONS
VALUES(SUPP_NAME,BATCH_NO,SYSDATE,QUANTITY);

EXCEPTION
WHEN Others THEN MANUFACTURER_NAME := '-1';
END;
/

CREATE OR REPLACE PROCEDURE REMOVE_EMPLOYEE(EMPID IN CHAR) IS
BEGIN
DELETE FROM EMPLOYEE WHERE EMPCODE = EMPID;
END;
/

CREATE OR REPLACE PROCEDURE RESET_ORDERID IS
BEGIN
UPDATE REFERENCE_VARIABLES SET NEXT_ORDERID = 'O0001';
END;
/