CREATE TABLE CUSTOMER (
ID CHAR(5) CONSTRAINT Pk_ID PRIMARY KEY CONSTRAINT Valid_Cust_Id CHECK (REGEXP_LIKE(ID, '^C[0-9]{4}$')),
Name VARCHAR(50),
Phone NUMBER(10) CONSTRAINT Valid_Phone CHECK (Phone NOT LIKE '0%' AND Phone NOT LIKE '1%' AND LENGTH(Phone) = 10) CONSTRAINT UNIQUE_PHONE UNIQUE,
Email VARCHAR(254) CONSTRAINT Valid_EmailID CHECK (Email LIKE '%@%.%') CONSTRAINT UNIQUE_EMAIL UNIQUE
);

CREATE TABLE ONLINE_PARTNERS (
NAME VARCHAR2(50) CONSTRAINT Pk_Partner_name PRIMARY KEY,
COMMISSION_PERCENT NUMBER(4,2));

CREATE TABLE ADDRESS(
ID CHAR(5) CONSTRAINT Pk_AddressID Primary key CONSTRAINT Valid_Address_Id CHECK (REGEXP_LIKE(ID, '^A[0-9]{4}$')),
Address_Line_1 VARCHAR(50),
City VARCHAR(50),
State VARCHAR(50),
Pincode NUMBER(6),
Country VARCHAR(50) CONSTRAINT Valid_Country CHECK(COUNTRY IN('AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANDORRA', 'ANGOLA', 'ANTIGUA AND BARBUDA', 'ARGENTINA', 'ARMENIA', 'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUS', 'BELGIUM', 'BELIZE', 'BENIN', 'BHUTAN', 'BOLIVIA', 'BOSNIA AND HERZEGOVINA', 'BOTSWANA', 'BRAZIL', 'BRUNEI', 'BULGARIA', 'BURKINA FASO', 'BURUNDI', 'CABO VERDE', 'CAMBODIA', 'CAMEROON', 'CANADA', 'CENTRAL AFRICAN REPUBLIC', 'CHAD', 'CHILE', 'CHINA', 'COLOMBIA', 'COMOROS', 'CONGO', 'COSTA RICA', 'CROATIA', 'CUBA', 'CYPRUS', 'CZECH REPUBLIC', 'DEMOCRATIC REPUBLIC OF THE CONGO', 'DENMARK', 'DJIBOUTI', 'DOMINICA', 'DOMINICAN REPUBLIC', 'ECUADOR', 'EGYPT', 'EL SALVADOR', 'EQUATORIAL GUINEA', 'ERITREA', 'ESTONIA', 'ESWATINI', 'ETHIOPIA', 'FIJI', 'FINLAND', 'FRANCE', 'GABON', 'GAMBIA', 'GEORGIA', 'GERMANY', 'GHANA', 'GREECE', 'GRENADA', 'GUATEMALA', 'GUINEA', 'GUINEA-BISSAU', 'GUYANA', 'HAITI', 'HONDURAS', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'IRELAND', 'ISRAEL', 'ITALY', 'JAMAICA', 'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA', 'KIRIBATI', 'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LEBANON', 'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES', 'MALI', 'MALTA', 'MARSHALL ISLANDS', 'MAURITANIA', 'MAURITIUS', 'MEXICO', 'MICRONESIA', 'MOLDOVA', 'MONACO', 'MONGOLIA', 'MONTENEGRO', 'MOROCCO', 'MOZAMBIQUE', 'MYANMAR', 'NAMIBIA', 'NAURU', 'NEPAL', 'NETHERLANDS', 'NEW ZEALAND', 'NICARAGUA', 'NIGER', 'NIGERIA', 'NORTH KOREA', 'NORTH MACEDONIA', 'NORWAY', 'OMAN', 'PAKISTAN', 'PALAU', 'PALESTINE', 'PANAMA', 'PAPUA NEW GUINEA', 'PARAGUAY', 'PERU', 'PHILIPPINES', 'POLAND', 'PORTUGAL', 'QATAR', 'ROMANIA', 'RUSSIA', 'RWANDA', 'SAINT KITTS AND NEVIS', 'SAINT LUCIA', 'SAINT VINCENT AND THE GRENADINES', 'SAMOA', 'SAN MARINO', 'SAO TOME AND PRINCIPE', 'SAUDI ARABIA', 'SENEGAL', 'SERBIA', 'SEYCHELLES', 'SIERRA LEONE', 'SINGAPORE', 'SLOVAKIA', 'SLOVENIA', 'SOLOMON ISLANDS', 'SOMALIA', 'SOUTH AFRICA', 'SOUTH KOREA', 'SOUTH SUDAN', 'SPAIN', 'SRI LANKA', 'SUDAN', 'SURINAME', 'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAJIKISTAN', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE', 'TOGO', 'TONGA', 'TRINIDAD AND TOBAGO', 'TUNISIA', 'TURKEY', 'TURKMENISTAN', 'TUVALU', 'UGANDA', 'UKRAINE', 'UNITED ARAB EMIRATES', 'UNITED KINGDOM', 'UNITED STATES OF AMERICA', 'URUGUAY', 'UZBEKISTAN', 'VANUATU', 'VATICAN CITY', 'VENEZUELA', 'VIETNAM', 'YEMEN', 'ZAMBIA', 'ZIMBABWE')),
CONSTRAINT PIN_NOT_NULL CHECK((COUNTRY='INDIA' AND PINCODE IS NOT NULL)OR(COUNTRY !='INDIA')));

CREATE TABLE EMPLOYEE(
EMPCODE CHAR(3) CONSTRAINT Pk_Empcode PRIMARY KEY CONSTRAINT Valid_Empcode CHECK (REGEXP_LIKE(EMPCODE, '^E[0-9]{2}$')),
FIRST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
SEX CHAR(1) CONSTRAINT Valid_Sex CHECK (SEX IN ('M', 'F', 'O')),
PHONE NUMBER(10) CONSTRAINT Valid_Phone_Emp CHECK (PHONE NOT LIKE '0%' AND PHONE NOT LIKE '1%' AND LENGTH(PHONE) = 10) CONSTRAINT UNIQUE_PHONE_EMP UNIQUE,
EMAIL VARCHAR(254) CONSTRAINT Valid_Email_Emp CHECK (EMAIL LIKE '%@%.%') CONSTRAINT UNIQUE_EMAIL_EMP UNIQUE,
ADDRESSID CHAR(5) CONSTRAINT Fk_Address REFERENCES ADDRESS);

CREATE TABLE ORDERS(
ORDERID CHAR(5) CONSTRAINT Valid_OrderID CHECK (REGEXP_LIKE(ORDERID,'^O[0-9]{4}$')),
DATE_OF_ORDER DATE,
EMPCODE CHAR(3) CONSTRAINT Fkey_Empcode REFERENCES EMPLOYEE,
ONLINE_PARTNER_NAME VARCHAR2(50) CONSTRAINT Fk_Online_Partner REFERENCES ONLINE_PARTNERS,
CUSTOMERID CHAR(5) CONSTRAINT Fk_CustomerID REFERENCES CUSTOMER,
CONSTRAINT Pk_OrderId_Date PRIMARY KEY (OrderID, Date_OF_ORDER),
CONSTRAINT ONLINE_OR_OFFLINE CHECK((ONLINE_PARTNER_NAME IS NULL AND EMPCODE IS NOT NULL)OR(ONLINE_PARTNER_NAME IS NOT NULL AND EMPCODE IS NULL)));

CREATE TABLE MANUFACTURER(
NAME VARCHAR2(50) CONSTRAINT Pk_Manu_Name PRIMARY KEY,
PHONE NUMBER(10) CONSTRAINT Valid_Manu_Phone CHECK (Phone NOT LIKE '0%' AND Phone NOT LIKE '1%' AND LENGTH(Phone) = 10) CONSTRAINT UNIQUE_PHONE_MANU UNIQUE,
EMAIL VARCHAR(254) CONSTRAINT Valid_Email_Manu CHECK (Email LIKE '%@%.%') CONSTRAINT UNIQUE_EMAIL_MANU UNIQUE,
BASE_LOCATION_ADDRESS_ID CHAR(5) CONSTRAINT Fk_Address_Manu REFERENCES ADDRESS);

CREATE TABLE ITEM(
BATCH_NO VARCHAR(20) CONSTRAINT Pk_Batch_No PRIMARY KEY,
ITEM_NAME VARCHAR(50),
MFD DATE,
EXP_DATE DATE,
COST_PRICE NUMBER(7,2),
SELLING_PRICE NUMBER(7,2),
STOCK NUMBER(4) CONSTRAINT Positive_Stock CHECK(STOCK>=0),
MANUFACTURER VARCHAR2(50) CONSTRAINT Fk_Manufacturer REFERENCES MANUFACTURER,
CONSTRAINT ExpDate_Greater_MFD CHECK(EXP_DATE>MFD));

CREATE TABLE ITEMS_ORDERED (
ORDERID CHAR(5),
DATE_OF_ORDER DATE,
BATCH_NO VARCHAR(20) CONSTRAINT Fk_BatchNo_Order REFERENCES ITEM,
QUANTITY NUMBER(3),
CONSTRAINT Fk_OrderID_Date FOREIGN KEY (ORDERID, DATE_OF_ORDER) REFERENCES ORDERS(OrderID, Date_OF_Order),
CONSTRAINT Pk_OrderID_BatchNo_Date PRIMARY KEY (ORDERID, BATCH_NO, DATE_OF_ORDER));


CREATE TABLE SUPPLIER(
NAME VARCHAR2(50) CONSTRAINT Pk_Supplier_name PRIMARY KEY,
PHONE NUMBER(10) CONSTRAINT Valid_Supply_Phone CHECK (Phone NOT LIKE '0%' AND Phone NOT LIKE '1%' AND LENGTH(Phone) = 10) CONSTRAINT UNIQUE_PHONE_SUPP UNIQUE,
EMAIL VARCHAR(254) CONSTRAINT Valid_Email_Supply CHECK (Email LIKE '%@%.%') CONSTRAINT UNIQUE_EMAIL_SUPP UNIQUE,
ADDRESS_ID CHAR(5) CONSTRAINT Fk_Address_Supply REFERENCES ADDRESS);

CREATE TABLE SUPPLY_TRANSACTIONS(
SUPPLIER_NAME VARCHAR2(50) CONSTRAINT Fk_Supplier_Name REFERENCES SUPPLIER,
BATCHNO VARCHAR(20) CONSTRAINT Fk_BatchNo_Supply REFERENCES ITEM,
DATE_OF_TRANSACTION DATE,
QUANTITY NUMBER(5),
CONSTRAINT Pk_Supplier_BatchNo PRIMARY KEY(SUPPLIER_NAME,BATCHNO));

CREATE TABLE REFERENCE_VARIABLES (
NEXT_ORDERID CHAR(5) CONSTRAINT Valid_Next_OrderID CHECK (REGEXP_LIKE(NEXT_ORDERID, '^O[0-9]{4}$')),
NEXT_CUSTOMERID CHAR(5) CONSTRAINT Valid_Next_CustID CHECK (REGEXP_LIKE(NEXT_CUSTOMERID, '^C[0-9]{4}$')),
NEXT_ADDRESSID CHAR(5) CONSTRAINT Valid_Next_AddressId CHECK(REGEXP_LIKE(NEXT_ADDRESSID, '^A[0-9]{4}$')),
NEXT_EMPCODE CHAR(3) CONSTRAINT Valid_Next_Empcode CHECK (REGEXP_LIKE(NEXT_EMPCODE, '^E[0-9]{2}$')));

INSERT INTO REFERENCE_VARIABLES VALUES('O0001','C0001','A0001','E01');







changes made:
table items ordered:
date to date_of_order
foreign key for both date_of_order and orderid
primary key now includes date of order as well

constraint name for EMAIL IN CUSTOMER CHANGED TO VALID_EMAILID
constraint name for EMPCODE IN ORDERS CHANGED TO Fkey_Empcode
ADDED CONSTRAINT UNIQUE_PHONE AND UNIQUE_EMAIL TO CUSTOMER.
ADDED CONSTRAINT UNIQUE_PHONE_EMP AND UNIQUE_EMAIL_EMP TO EMPLOYEE.
ADDED CONSTRAINT ONLINE_OR_OFFLINE TO ORDERS.
ADDED CONSTRAINT UNIQUE_PHONE_MANU AND UNIQUE_EMAIL_MANU TO MANUFACTURER
constraint name for primary key IN items_ordered CHANGED TO Pk_OrderID_BatchNo_Date
ADDED CONSTRAINT UNIQUE_PHONE_SUPP AND UNIQUE_EMAIL_SUPP TO SUPPLIER
changed online_partners commission_percent to number(4,2)
CHANGED CP AND SP IN ITEM TO NUMBER(7,2)

table supply_transactions:
a new date_of_transaction column has been added

A new table reference_variables has been created with 1 row of data inserted.

























